@url = https://lotteryapis.herokuapp.com/api/v1

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5MjBmYTdmNy1lNTIwLTRmZjctYmY2NS1kMDEwYmU3NzkxMDMiLCJqdGkiOiIwOTI5Y2ZiZGY5MGNhYzlkMjFjOWQ1NjE2ZjllMGRiMWNjZDU5MmNiMzI0MTA2OTU5OTE2YTdiMjdlNDRkMDBiOWNkMjQzZGFkZDhjNjdjMyIsImlhdCI6MTYwNTk1OTU5NiwibmJmIjoxNjA1OTU5NTk2LCJleHAiOjE2Mzc0OTU1OTYsInN1YiI6IjEiLCJzY29wZXMiOlsidXNlciJdfQ.SVKREsZc2Mx-lEd2bSrlXAMI-O1E01G3STA8ornfGb0Vbnkab1MPK4sG7uWC2fV-i6F2DuLfzd3o_hkJ4wCxVw

@appKey = chitgyi

###
POST {{url}}/register
Content-Type: application/json
Accept: application/json
app-key: {{appKey}}

{
    "name": "Chit Ye", 
    "email": "chityeaun@gmail.com",
    "password": "chityeaung"
}

###

POST {{url}}/login
app-key: {{appKey}}
Content-Type: application/json
Accept: application/json

{
    "email": "chityeaung@gmail.com",
    "password": "password"
}
###

GET {{url}}/profile
app-key: {{appKey}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
